### ISSUE TITLE
Faraday::RackBuilder::StackLocked: can't modify middleware stack after making a request

### ISSUE THREAD

**Issue by masterkain** [oauth-xx/oauth2#173]
I'm using oauth2 in a sidekiq worker. Faraday 0.9.0, oauth2 from master.
The first time it runs I get this error:

```
Faraday::RackBuilder::StackLocked
20:50:58 workers.1 | 2014-05-07T18:50:58Z 60220 TID-ouufoa6is WARN: can't modify middleware stack after making a request
20:50:58 workers.1 | 2014-05-07T18:50:58Z 60220 TID-ouufoa6is WARN: /Users/kain/.rvm/gems/ruby-2.1.1/gems/faraday-0.9.0/lib/faraday/rack_builder.rb:199:in `raise_if_locked'
20:50:58 workers.1 | /Users/kain/.rvm/gems/ruby-2.1.1/gems/faraday-0.9.0/lib/faraday/rack_builder.rb:86:in `use'
20:50:58 workers.1 | /Users/kain/.rvm/gems/ruby-2.1.1/gems/faraday-0.9.0/lib/faraday/rack_builder.rb:203:in `use_symbol'
20:50:58 workers.1 | /Users/kain/.rvm/gems/ruby-2.1.1/gems/faraday-0.9.0/lib/faraday/rack_builder.rb:96:in `response'
20:50:58 workers.1 | /Users/kain/.rvm/gems/ruby-2.1.1/bundler/gems/oauth2-cd8a62e69cab/lib/oauth2/client.rb:89:in `request'
20:50:58 workers.1 | /Users/kain/.rvm/gems/ruby-2.1.1/bundler/gems/oauth2-cd8a62e69cab/lib/oauth2/access_token.rb:107:in `request'
20:50:58 workers.1 | /Users/kain/.rvm/gems/ruby-2.1.1/bundler/gems/oauth2-cd8a62e69cab/lib/oauth2/access_token.rb:114:in `get'
```

**Comment by alepore** [comment]
Similar problem, it was `OAUTH_DEBUG=true`
see https://github.com/intridea/oauth2/issues/189

**Comment by josephpage** [comment]
Fixed in #294 and #142 
Will be shipped in next release.

**Comment by lastgabs** [comment]
I'm in version 1.4.1 and faraday 0.12.2 and still seeing this error.
```
2019-03-07 19:50:10 +0000: Rack app error handling request { GET  }
#<Faraday::RackBuilder::StackLocked: can't modify middleware stack after making a request>
```

Is there something we could do debug this further?

**Comment by pboling** [comment]
@lastgabs It would probably be a good idea to move to a newer release of faraday.  The gem says it is compatible with older versions of faraday, but that's only because we don't know that it is broken with them.  Old versions of faraday may well be broken!

**Comment by syakovyn** [comment]
I have the same issue with oauth2 1.4.1 and faraday 0.15.4 (as far as I can see that's the latest version). How could I help with investigating the issue?

**Comment by pboling** [comment]
Can you give a stack trace, or repro inside the spec suite on a fork, or try to give steps to repro in a fully-aspirated example app?

**Comment by lastgabs** [comment]
Here's my stack trace:
```
Puma caught this error: can't modify middleware stack after making a request (Faraday::RackBuilder::StackLocked)
/app/vendor/bundle/ruby/2.5.0/gems/faraday-0.12.2/lib/faraday/rack_builder.rb:202:in `raise_if_locked'
/app/vendor/bundle/ruby/2.5.0/gems/faraday-0.12.2/lib/faraday/rack_builder.rb:86:in `use'
/app/vendor/bundle/ruby/2.5.0/gems/faraday-0.12.2/lib/faraday/rack_builder.rb:226:in `use_symbol'
/app/vendor/bundle/ruby/2.5.0/gems/faraday-0.12.2/lib/faraday/rack_builder.rb:97:in `response'
/app/vendor/bundle/ruby/2.5.0/gems/oauth2-1.4.0/lib/oauth2/client.rb:95:in `request'
/app/vendor/bundle/ruby/2.5.0/gems/oauth2-1.4.0/lib/oauth2/access_token.rb:107:in `request'
/app/vendor/bundle/ruby/2.5.0/gems/oauth2-1.4.0/lib/oauth2/access_token.rb:114:in `get'
/app/sd.rb:111:in `email_from_auth_code'
/app/sd.rb:72:in `authenticated_email'
/app/sd.rb:218:in `sd_callback'
/app/vendor/bundle/ruby/2.5.0/bundler/gems/lita-81121a81ead8/lib/lita/callback.rb:31:in `public_send'
/app/vendor/bundle/ruby/2.5.0/bundler/gems/lita-81121a81ead8/lib/lita/callback.rb:31:in `call'
/app/vendor/bundle/ruby/2.5.0/bundler/gems/lita-81121a81ead8/lib/lita/http_callback.rb:26:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/http_router-0.11.2/lib/http_router.rb:193:in `process_destination_path'
(eval):89:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/http_router-0.11.2/lib/http_router.rb:288:in `raw_call'
/app/vendor/bundle/ruby/2.5.0/bundler/gems/lita-81121a81ead8/lib/lita/rack_app.rb:46:in `call'
/app/http_logger.rb:15:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/buffered-logger-2.0.0/lib/buffered_logger/middleware.rb:8:in `block in call'
/app/vendor/bundle/ruby/2.5.0/gems/buffered-logger-2.0.0/lib/buffered_logger.rb:30:in `start'
/app/vendor/bundle/ruby/2.5.0/gems/buffered-logger-2.0.0/lib/buffered_logger/middleware.rb:8:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/bugsnag-6.6.4/lib/bugsnag/integrations/rack.rb:46:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/puma-3.12.0/lib/puma/server.rb:658:in `handle_request'
/app/vendor/bundle/ruby/2.5.0/gems/puma-3.12.0/lib/puma/server.rb:472:in `process_client'
/app/vendor/bundle/ruby/2.5.0/gems/puma-3.12.0/lib/puma/server.rb:332:in `block in run'
/app/vendor/bundle/ruby/2.5.0/gems/puma-3.12.0/lib/puma/thread_pool.rb:133:in `block in spawn_thread'
```

We have OAuth making a request and I set `ENV['OAUTH_DEBUG'] = 'true'` as per the directions [here](https://github.com/oauth-xx/oauth2#debugging). Let me know if there's anything else I can provide to make it easier to debug.

**Comment by syakovyn** [comment]
Hi @pboling,

I've checked the repo and found that https://github.com/oauth-xx/oauth2/pull/294 is missing in 1.4.1 release. I've added that test and was able to reproduce the issue.

Adding that test to 1-4-stable with a change I made a comment about in https://github.com/oauth-xx/oauth2/pull/294 reproduces the issue exactly as I'm seeing it.

**Comment by pboling** [comment]
@gafrom do you have any ideas about this, as you worked on something related in #294 ?

**Comment by markfrst** [comment]
i removed from the faraday gem follow line (https://github.com/lostisland/faraday/blob/master/lib/faraday/rack_builder.rb#L165) and it fix for me

**Comment by gafrom** [comment]
@pboling, as far as I can see - the fix cd104e84485b6185f1cac49b2f4b6ae2520e670f was set to be added to the **1.5.0** milestone. And sure I do not see fixed `client.rb` in **v1.4.1**.
So, unsurprisingly, @lastgabs is still experiencing the issue.

**Comment by pboling** [comment]
@galois17 That makes sense!  @lastgabs @syakovyn @masterkain Would you be able to try using the master branch to see if the issue is resolved?  We're still working toward a new major release.

**Comment by BrunoQuaresma** [comment]
updates?

**Comment by pboling** [comment]
@BrunoQuaresma See the comment above yours.  We are waiting on feedback from the community.  If you are using `master` branch this should no longer be an issue.  Please verify if that is the case for you!

**Comment by pboling** [comment]
Within a week, this issue will be closed so we can move forward with the 2.0.0 release, if there is no negative feedback.

**Comment by BrunoQuaresma** [comment]
thanks @pboling
